[package]
name = "snake-rust"
version = "0.1.0"
edition = "2021"
authors = ["imbianchi"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "^0.130"
rand = "0.8"
